=== webdetails/ccc/doc/schema/com_2012.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2030-06-15
 ******************************************************************************* -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="urn:webdetails/com/2012" 
        xmlns:com="urn:webdetails/com/2012" 
        elementFormDefault="qualified">
    
    <!-- 
        List(number) 
        
        Union(string number)
        
        Union(string number List(number))
        
        List(Union(string number))
        
        Union(string number List(Union(string number))
        
        Map(string Object)
        
        Invalid combinations:
          X  List(List(.))
          X  List(Union(List(.) number))
          X  Map(string Map(.))       ??? TODO
          X  Map(string List(Map(.))) ???
          
          X  cycles...
          
        ......................................................
         
                /
          Value | * name  (Lists and Unions may be anonymous)
            ^   \
            |
            |              /
            |....... Union | * types -> Value
            |              \
            |
            |              /
            |....... List  | * elementType -> Item
            |              \
            |
            |              /
            |....... Map   | * keyType   -> Item
            |              | * valueType -> Item // TODO need this restriction?
            |              \
            |
            +....... Item
                       ^
                       |
                       |                     /
                       |.......... ItemUnion | * types -> Item
                       |                     \
                       |
                       |.......... Atom
                       |             ^
                       |             |
                       |             +...... Primitive
                       |
                       |                   /
                       +.......... Complex | * abstract
                                        |  | * baseType -> Complex 
                                        |  \
                                        |                     /
                                        |                     | * name
                                        +........ >> Property | * required
                                                              | * default
                                                              \ 
     -->
     
    <element name="model" type="com:ModelType">
        <!-- Splitting in several files renders these undesirable 
        
        <key name="complexType_unique_name">
            <selector xpath="com:complexType" />
            <field xpath="@space" />
            <field xpath="@name" />
        </key>
        
        <key name="atomType_unique_name">
            <selector xpath="com:atomType" />
            <field xpath="@name" />
        </key>
        
        <key name="funType_unique_name">
            <selector xpath="com:functionType" />
            <field xpath="@name" />
        </key>
        
        <key name="space_unique_name">
            <selector xpath="com:space" />
            <field xpath="@name" />
        </key>
        
         -->
         
        <unique name="model_documentation_format_key">
           <selector xpath="." />
           <field xpath="documentation/@format" />
        </unique>
        
        <unique name="class_documentation_format_key">
           <selector xpath="com:complexType" />
           <field xpath="documentation/@format" />
        </unique>
        
        <unique name="property_documentation_format_key">
           <selector xpath="com:complexType/property" />
           <field xpath="documentation/@format" />
        </unique>
        
        <!-- does not work because of namespace being split in class_key 
        <keyref name="class_keyref" refer="com:class_key">
            <selector xpath="com:complexType" />
            <field xpath="@base" />
        </keyref>
         -->
    </element>
    
    <!-- Elements to be used inside c:documentation elements -->
    <element name="link">
        <complexType>
            <attribute name="to" type="string" use="required" />
        </complexType>
    </element>
    
    <element name="example">
        <complexType mixed="true">
	        <sequence minOccurs="0" maxOccurs="unbounded">
	            <any namespace="##any" processContents="lax" />
	        </sequence>
        </complexType>
    </element>
    
    <element name="deprecated">
        <complexType mixed="true">
            <sequence minOccurs="0" maxOccurs="unbounded">
                <any namespace="##any" processContents="lax" />
            </sequence>
        </complexType>
    </element>
    
    <!-- Model XSD types -->
    
    <complexType name="ModelType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <choice minOccurs="0" maxOccurs="unbounded">
                <element name="space" type="com:SpaceType" />
	            <element name="complexType" type="com:ComplexTypeType">
	                <key name="complex_unique_prop_name">
                        <selector xpath="com:property" />
                        <field xpath="@name" />
                    </key>
	            </element>
	            <element name="atomType" type="com:AtomTypeType">
	                <key name="atom_unique_name">
			            <selector xpath="com:atom" />
			            <field xpath="@name" />
			        </key>
			        <key name="atom_unique_value">
			            <selector xpath="com:atom" />
			            <field xpath="@value" />
			        </key>
	            </element>
	            <element name="functionType" type="com:FunctionTypeType" />
	            <element name="facetType" type="com:FacetTypeType" />
	            <element name="include">
			        <complexType>
			            <attribute name="the" type="string" use="required" /> 
			        </complexType>
			    </element>
	       </choice>
       </sequence>
    </complexType>
    
    <complexType name="SpaceType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
       </sequence>
       <attribute name="name" type="com:IdType" use="required" />
    </complexType>
    
    <complexType name="ComplexTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="property" type="com:PropertyType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <attribute name="base" type="com:IdType" />
        <attribute name="facets" type="com:IdTypeList" />
        <attribute name="abstract" type="boolean" default="false" />
        <attribute name="use" type="com:ComplexUseType" default="literal" />
    </complexType>
    
    <complexType name="FacetTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="property" type="com:PropertyType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <!-- 
        <attribute name="base" type="com:IdType" />
        <attribute name="abstract" type="boolean" default="false" />
         -->
    </complexType>
    
    <complexType name="PropertyType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="type" type="com:ValueTypeType" default="string" />
        <attribute name="required" type="boolean" default="false" />
        <attribute name="default" type="anySimpleType" />
        <attribute name="fixed" type="anySimpleType" />
        <attribute name="category" type="string" />
        <attribute name="expandUse" type="com:PropertyExpandUseType" default="required" />
        <attribute name="excludeIn" type="NMTOKENS" /> 
        <attribute name="level" type="com:PropertyLevelType" default="advanced" />
    </complexType>
    
    <complexType name="AtomTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="atom" type="com:AtomType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <attribute name="base" type="com:IdType" />
    </complexType>
    
    <complexType name="AtomType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name"  type="com:IdType" use="required" />
        <attribute name="value" type="anySimpleType" use="required" />
    </complexType>
    
    <complexType name="FunctionTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="argument" type="com:ArgumentType" minOccurs="0" maxOccurs="unbounded" />
            <element name="returns"  type="com:ReturnType" minOccurs="0" maxOccurs="1" />
        </sequence>
        
        <attribute name="name"  type="com:IdType" use="required" />
        <attribute name="space" type="string" />
    </complexType>
    
    <complexType name="ArgumentType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="type" type="com:ValueTypeType" use="optional" default="undefined" />
        <attribute name="required" type="boolean" default="false" />
        <attribute name="default" type="anySimpleType" use="optional" />
    </complexType>
    
    <complexType name="ReturnType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="type" type="com:ValueTypeType" use="optional" default="undefined" />
    </complexType>
    
    <complexType name="DocumentationType" mixed="true">
        <sequence minOccurs="0" maxOccurs="unbounded">
            <any namespace="##any" processContents="lax" />
        </sequence>
        
        <attribute name="format" type="com:DocumentationFormatType" use="optional" />
    </complexType>
    
    <simpleType name="ValueTypeType">
        <union memberTypes="com:PrimitiveSimpleTypeType string" />
    </simpleType>
    
    <simpleType name="PrimitiveSimpleTypeType">
        <restriction base="string">
            <enumeration value="undefined" />
            <enumeration value="literal" />
            <enumeration value="string" />
            <enumeration value="number" />
            <enumeration value="boolean" />
            <enumeration value="object" />
            <enumeration value="function" />
            <enumeration value="date" />
            <enumeration value="percentage" />
        </restriction>
    </simpleType>
    
    <simpleType name="ComplexUseType">
        <restriction base="string">
            <enumeration value="literal" />
            <enumeration value="expanded" />
            <enumeration value="any" />
        </restriction>
    </simpleType>
    
    <simpleType name="PropertyExpandUseType">
        <restriction base="string">
            <enumeration value="optional" />
            <enumeration value="required" />
        </restriction>
    </simpleType>
    
    <!-- A measure of difficulty or frequency of use of a property -->
    <simpleType name="PropertyLevelType">
        <restriction base="string">
            <enumeration value="basic" />
            <enumeration value="intermediate" />
            <enumeration value="advanced" />
        </restriction>
    </simpleType>
    
    <simpleType name="IdType">
        <restriction base="NMTOKEN" />
    </simpleType>
    
    <simpleType name="IdTypeList">
        <list itemType="com:IdType" />
    </simpleType>
    
    <simpleType name="DocumentationFormatType">
        <restriction base="string">
           <enumeration value="markdown" />
           <enumeration value="jsdoc" />
           <enumeration value="com" />
        </restriction>
    </simpleType>
</schema>

=== webdetails/ccc/doc/model/panels/common.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2030-06-15
 ******************************************************************************* -->
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:complexType name="Panel" 
                   space="pvc.options.panels"
                   abstract="true">
        <c:documentation>
            The common options documentation class of the CCC panels.
        </c:documentation>
        
        <c:property name="size" type="number string pvc.options.varia.Size" category="Layout">
            <c:documentation>
                The fixed size of the panel, in pixel units or as a percentage.
                
                See <c:link to="pvc.options.varia.Size" /> for information about 
                the different supported data types.
            </c:documentation>
        </c:property>
        
        <c:property name="sizeMax" type="number string pvc.options.varia.Size" category="Layout">
            <c:documentation>
                The maximum size of the panel, in pixel units or as a percentage.
                
                See <c:link to="pvc.options.varia.Size" /> for information about 
                the different supported data types.
            </c:documentation>
        </c:property>
    </c:complexType>
    
</c:model>

=== webdetails/ccc/doc/model/varia/functions/dimensionConverter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2030-06-15
 ******************************************************************************* -->
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:functionType name="DimensionConverter" space="pvc.options.varia">
        <c:documentation>
            A function that converts a non-null raw value
            into a value of the dimension's 
            <c:link to="pvc.options.DimensionType#valueType" />
            or some value that 
            its cast function can convert from.
        </c:documentation>
        <c:argument name="this" type="null" required="true">
            <c:documentation>
                The global JavaScript object.
            </c:documentation>
        </c:argument>
        <c:argument name="sourceValue" type="any" required="true">
            <c:documentation>
                The non-null source value to convert.
                
                In the case where the raw value to convert is 
                a Google-table-like cell, 
                it is the value of its <tt>v</tt>
                property that is passed to this argument.
            </c:documentation>
        </c:argument>
        <c:returns type="any">
            <c:documentation>
                The converted value.
            </c:documentation>
        </c:returns>
    </c:functionType>
</c:model>

=== webdetails/ccc/doc/model/varia/functions/userSelectionAction.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2030-06-15
 ******************************************************************************* -->
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:functionType name="UserSelectionAction" space="pvc.options.varia">
        <c:documentation>
            A callback function that is called
            when the user performs a selection,
            but before the corresponding datums' selected state is actually changed.
        </c:documentation>
        <c:argument name="this" type="pvc.visual.Context" required="true">
            <c:documentation>
                The CCC visual context object.
            </c:documentation>
        </c:argument>
        <c:argument name="selectingDatums" type="list(pvc.data.Datum)" required="true">
            <c:documentation>
                An array with the datums that will be selected by the current operation.
            </c:documentation>
        </c:argument>
        <c:argument name="selectingGroup" type="pvc.data.Data">
            <c:documentation>
                A data group, if the current operation will only select a single group, otherwise no
                value.
            </c:documentation>
        </c:argument>
        <c:returns type="list(pvc.data.Datum)">
            <c:documentation>
                The datums that should be actually selected.
            </c:documentation>
        </c:returns>
    </c:functionType>
</c:model>

=== webdetails/ccc/doc/model/varia/atoms/lineAreaInterpolation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2030-06-15
 ******************************************************************************* -->
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:atomType name="LineAreaInterpolation" space="pvc.options.varia" base="string">
        <c:documentation>
            How to interpolate the line or area between values.
            
            See the associated protovis documentation at
            <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Line.html#interpolate" />
            and
            <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Area.html#interpolate" />.
            
            Protovis supports other interpolation values, 
            but these do not work well with the CCC point charts. 
        </c:documentation>
        
        <c:atom name="Linear" value="'linear'">
            <c:documentation>
                Produces a straight line between points.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Basis" value="'basis'">
            <c:documentation>
                Produces an open uniform <b>b</b>-spline.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Cardinal" value="'cardinal'">
            <c:documentation>
                Produces cardinal splines.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Monotone" value="'monotone'">
            <c:documentation>
                Produces a Fritsch-Carlson 
                monotone cubic hermite interpolation.
            </c:documentation>
        </c:atom>
        
    </c:atomType>
</c:model>

=== webdetails/ccc/doc/model/varia/atoms/panelAlignment.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2030-06-15
 ******************************************************************************* -->
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">

    <c:atomType name="PanelAlignmentSource" space="pvc.options.varia" base="string">
        <c:documentation>
            The sides of a child panel, the source, 
            that can be aligned with 
            a target side of a parent panel.
            
            The alignment side must be 
            orthogonal to the side of 
            the <c:link to="pvc.options.varia.PanelPosition" />.
            
            By combining the alignment source
            with the <c:link to="pvc.options.varia.PanelAlignmentTarget"/>,
            different alignment combinations can be achieved.
            
            The alignment target side must be 
            parallel to the side of source alignment.
        </c:documentation>
        
        <c:atom name="Left" value="'left'">
            <c:documentation>
                The left side of the child panel 
                is placed at the same position as the
                target side of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Center" value="'center'">
            <c:documentation>
                The horizontal center position of the child panel 
                is placed at the same position as the
                target side of the parent panel. 
            </c:documentation>
        </c:atom>
        
        <c:atom name="Right" value="'right'">
            <c:documentation>
                The right side of the child panel 
                is placed at the same position as the
                target side of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Top" value="'top'">
            <c:documentation>
                The top side of the child panel 
                is placed at the same position as the
                target side of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Middle" value="'middle'">
            <c:documentation>
                The vertical center position of the child panel 
                is placed at the same position as the
                target side of the parent panel. 
            </c:documentation>
        </c:atom>
        
        <c:atom name="Bottom" value="'bottom'">
            <c:documentation>
                The bottom side of the child panel 
                is placed at the same position as the
                target side of the parent panel. 
            </c:documentation>
        </c:atom>
    </c:atomType>
    
    <c:atomType name="PanelAlignmentTarget" space="pvc.options.varia" base="string">
        <c:documentation>
            The sides of a parent panel, the target, 
            with which the alignment side of a source child panel 
            can be aligned to.
            
            The alignment target side must be 
            parallel to the side of source alignment.
            
            Wherever an alignment target argument is found,
            a value of type <tt>number</tt>,
            a numeric <tt>string</tt> or 
            a numeric percentage <tt>string</tt>, 
            may also be specified.
            
            In this case, 
            these specify the position of alignment, 
            from the left or top sides,
            whichever is parallel to the alignment source side.
            
            For example, if the source alignment side is <tt>'right'</tt>
            and the target alignment specifies <tt>'10%'</tt>,
            then the right side of the child panel would be
            placed at a position of 
            10% of the parent panel's client width
            from the parent's left side.
        </c:documentation>
        
        <c:atom name="Left" value="'left'">
            <c:documentation>
                The source side of the child panel
                is placed at the same position as the
                left side of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Center" value="'center'">
            <c:documentation>
                The source side of the child panel
                is placed at the same position as the
                horizontal center position of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Right" value="'right'">
            <c:documentation>
                The source side of the child panel
                is placed at the same position as the
                right side of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Top" value="'top'">
            <c:documentation>
                The source side of the child panel
                is placed at the same position as the
                top side of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Middle" value="'middle'">
            <c:documentation>
                The source side of the child panel
                is placed at the same position as the
                vertical center position of the parent panel.
            </c:documentation>
        </c:atom>
        
        <c:atom name="PageMiddle" value="'page-middle'">
            <c:documentation>
                The source side of the child panel
                is placed at the same position as the
                vertical center position of the 
                <i>page</i> height of the parent panel.
                
                The page height differs from the chart height
                in that the 
                page height is by definition 
                the value initially specified in 
                <c:link to="pvc.options.charts.BasicChart#height" />,
                and the chart height 
                can grow if layout so requires it,
                like it does in <i>small multiples</i> charts.
                
                The page middle alignment allows, 
                for example, 
                placing the legend panel in 
                the middle of the screen height,
                even though the height of the chart
                may have become much larger.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Bottom" value="'bottom'">
            <c:documentation>
                The source side of the child panel
                is placed at the same position as the
                bottom side of the parent panel.
            </c:documentation>
        </c:atom>
    </c:atomType>
    
</c:model>
