=== webdetails/ccc/doc/schema/com_2012.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2030-06-15
 ******************************************************************************* -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
        targetNamespace="urn:webdetails/com/2012" 
        xmlns:com="urn:webdetails/com/2012" 
        elementFormDefault="qualified">
    
    <!-- 
        List(number) 
        
        Union(string number)
        
        Union(string number List(number))
        
        List(Union(string number))
        
        Union(string number List(Union(string number))
        
        Map(string Object)
        
        Invalid combinations:
          X  List(List(.))
          X  List(Union(List(.) number))
          X  Map(string Map(.))       ??? TODO
          X  Map(string List(Map(.))) ???
          
          X  cycles...
          
        ......................................................
         
                /
          Value | * name  (Lists and Unions may be anonymous)
            ^   \
            |
            |              /
            |....... Union | * types -> Value
            |              \
            |
            |              /
            |....... List  | * elementType -> Item
            |              \
            |
            |              /
            |....... Map   | * keyType   -> Item
            |              | * valueType -> Item // TODO need this restriction?
            |              \
            |
            +....... Item
                       ^
                       |
                       |                     /
                       |.......... ItemUnion | * types -> Item
                       |                     \
                       |
                       |.......... Atom
                       |             ^
                       |             |
                       |             +...... Primitive
                       |
                       |                   /
                       +.......... Complex | * abstract
                                        |  | * baseType -> Complex 
                                        |  \
                                        |                     /
                                        |                     | * name
                                        +........ >> Property | * required
                                                              | * default
                                                              \ 
     -->
     
    <element name="model" type="com:ModelType">
        <!-- Splitting in several files renders these undesirable 
        
        <key name="complexType_unique_name">
            <selector xpath="com:complexType" />
            <field xpath="@space" />
            <field xpath="@name" />
        </key>
        
        <key name="atomType_unique_name">
            <selector xpath="com:atomType" />
            <field xpath="@name" />
        </key>
        
        <key name="funType_unique_name">
            <selector xpath="com:functionType" />
            <field xpath="@name" />
        </key>
        
        <key name="space_unique_name">
            <selector xpath="com:space" />
            <field xpath="@name" />
        </key>
        
         -->
         
        <unique name="model_documentation_format_key">
           <selector xpath="." />
           <field xpath="documentation/@format" />
        </unique>
        
        <unique name="class_documentation_format_key">
           <selector xpath="com:complexType" />
           <field xpath="documentation/@format" />
        </unique>
        
        <unique name="property_documentation_format_key">
           <selector xpath="com:complexType/property" />
           <field xpath="documentation/@format" />
        </unique>
        
        <!-- does not work because of namespace being split in class_key 
        <keyref name="class_keyref" refer="com:class_key">
            <selector xpath="com:complexType" />
            <field xpath="@base" />
        </keyref>
         -->
    </element>
    
    <!-- Elements to be used inside c:documentation elements -->
    <element name="link">
        <complexType>
            <attribute name="to" type="string" use="required" />
        </complexType>
    </element>
    
    <element name="example">
        <complexType mixed="true">
	        <sequence minOccurs="0" maxOccurs="unbounded">
	            <any namespace="##any" processContents="lax" />
	        </sequence>
        </complexType>
    </element>
    
    <element name="deprecated">
        <complexType mixed="true">
            <sequence minOccurs="0" maxOccurs="unbounded">
                <any namespace="##any" processContents="lax" />
            </sequence>
        </complexType>
    </element>
    
    <!-- Model XSD types -->
    
    <complexType name="ModelType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <choice minOccurs="0" maxOccurs="unbounded">
                <element name="space" type="com:SpaceType" />
	            <element name="complexType" type="com:ComplexTypeType">
	                <key name="complex_unique_prop_name">
                        <selector xpath="com:property" />
                        <field xpath="@name" />
                    </key>
	            </element>
	            <element name="atomType" type="com:AtomTypeType">
	                <key name="atom_unique_name">
			            <selector xpath="com:atom" />
			            <field xpath="@name" />
			        </key>
			        <key name="atom_unique_value">
			            <selector xpath="com:atom" />
			            <field xpath="@value" />
			        </key>
	            </element>
	            <element name="functionType" type="com:FunctionTypeType" />
	            <element name="facetType" type="com:FacetTypeType" />
	            <element name="include">
			        <complexType>
			            <attribute name="the" type="string" use="required" /> 
			        </complexType>
			    </element>
	       </choice>
       </sequence>
    </complexType>
    
    <complexType name="SpaceType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
       </sequence>
       <attribute name="name" type="com:IdType" use="required" />
    </complexType>
    
    <complexType name="ComplexTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="property" type="com:PropertyType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <attribute name="base" type="com:IdType" />
        <attribute name="facets" type="com:IdTypeList" />
        <attribute name="abstract" type="boolean" default="false" />
        <attribute name="use" type="com:ComplexUseType" default="literal" />
    </complexType>
    
    <complexType name="FacetTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="property" type="com:PropertyType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <!-- 
        <attribute name="base" type="com:IdType" />
        <attribute name="abstract" type="boolean" default="false" />
         -->
    </complexType>
    
    <complexType name="PropertyType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="type" type="com:ValueTypeType" default="string" />
        <attribute name="required" type="boolean" default="false" />
        <attribute name="default" type="anySimpleType" />
        <attribute name="fixed" type="anySimpleType" />
        <attribute name="category" type="string" />
        <attribute name="expandUse" type="com:PropertyExpandUseType" default="required" />
        <attribute name="excludeIn" type="NMTOKENS" /> 
        <attribute name="level" type="com:PropertyLevelType" default="advanced" />
    </complexType>
    
    <complexType name="AtomTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="atom" type="com:AtomType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="space" type="string" />
        <attribute name="base" type="com:IdType" />
    </complexType>
    
    <complexType name="AtomType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name"  type="com:IdType" use="required" />
        <attribute name="value" type="anySimpleType" use="required" />
    </complexType>
    
    <complexType name="FunctionTypeType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
            <element name="argument" type="com:ArgumentType" minOccurs="0" maxOccurs="unbounded" />
            <element name="returns"  type="com:ReturnType" minOccurs="0" maxOccurs="1" />
        </sequence>
        
        <attribute name="name"  type="com:IdType" use="required" />
        <attribute name="space" type="string" />
    </complexType>
    
    <complexType name="ArgumentType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="name" type="com:IdType" use="required" />
        <attribute name="type" type="com:ValueTypeType" use="optional" default="undefined" />
        <attribute name="required" type="boolean" default="false" />
        <attribute name="default" type="anySimpleType" use="optional" />
    </complexType>
    
    <complexType name="ReturnType">
        <sequence>
            <element name="documentation" type="com:DocumentationType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="type" type="com:ValueTypeType" use="optional" default="undefined" />
    </complexType>
    
    <complexType name="DocumentationType" mixed="true">
        <sequence minOccurs="0" maxOccurs="unbounded">
            <any namespace="##any" processContents="lax" />
        </sequence>
        
        <attribute name="format" type="com:DocumentationFormatType" use="optional" />
    </complexType>
    
    <simpleType name="ValueTypeType">
        <union memberTypes="com:PrimitiveSimpleTypeType string" />
    </simpleType>
    
    <simpleType name="PrimitiveSimpleTypeType">
        <restriction base="string">
            <enumeration value="undefined" />
            <enumeration value="literal" />
            <enumeration value="string" />
            <enumeration value="number" />
            <enumeration value="boolean" />
            <enumeration value="object" />
            <enumeration value="function" />
            <enumeration value="date" />
            <enumeration value="percentage" />
        </restriction>
    </simpleType>
    
    <simpleType name="ComplexUseType">
        <restriction base="string">
            <enumeration value="literal" />
            <enumeration value="expanded" />
            <enumeration value="any" />
        </restriction>
    </simpleType>
    
    <simpleType name="PropertyExpandUseType">
        <restriction base="string">
            <enumeration value="optional" />
            <enumeration value="required" />
        </restriction>
    </simpleType>
    
    <!-- A measure of difficulty or frequency of use of a property -->
    <simpleType name="PropertyLevelType">
        <restriction base="string">
            <enumeration value="basic" />
            <enumeration value="intermediate" />
            <enumeration value="advanced" />
        </restriction>
    </simpleType>
    
    <simpleType name="IdType">
        <restriction base="NMTOKEN" />
    </simpleType>
    
    <simpleType name="IdTypeList">
        <list itemType="com:IdType" />
    </simpleType>
    
    <simpleType name="DocumentationFormatType">
        <restriction base="string">
           <enumeration value="markdown" />
           <enumeration value="jsdoc" />
           <enumeration value="com" />
        </restriction>
    </simpleType>
</schema>

=== webdetails/ccc/doc/model/varia/atoms/dataTypeCheckingMode.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2030-06-15
 ******************************************************************************* -->
<c:model
    xmlns:c="urn:webdetails/com/2012"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">

    <c:atomType name="DataTypeCheckingMode" space="pvc.options.varia" base="string">
        <c:documentation>
            The confirmation mode of the column types declared in a dataset's metadata.

            The column type metadata is sometimes incorrect
            due to the existence of nulls in the first row and
            the inability of some data sources to
            properly identify the data type in that case.

            Other times, its incorrect just because...
            "Numeric" columns may be declared as "String",
            and contain either numbers or numeric strings.
        </c:documentation>

        <c:atom name="None" value="'none'">
            <c:documentation>
                Trusts the data source column type metadata.
            </c:documentation>
        </c:atom>

        <c:atom name="Minimum" value="'minimum'">
            <c:documentation>
                Checks if columns declared as "String" are "Numeric",
                based on the type of first non-null value.

                The column type is established by the
                first row in which the column value is non-null.
                The type will be considered "Numeric" if the
                value is a JavaScript number.
            </c:documentation>
        </c:atom>

        <c:atom name="Extended" value="'extended'">
            <c:documentation>
                Checks if columns declared as "String" are "Numeric",
                based on the type and form of the first non-null value.

                The column type is established by the
                first row in which the column value is non-null.
                The type will be considered "Numeric" if the
                value is a JavaScript number <i>or</i>
                if it can be parsed as a number.
            </c:documentation>
        </c:atom>
    </c:atomType>
</c:model>

=== webdetails/ccc/doc/model/marks/dot.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2030-06-15
 ******************************************************************************* -->
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:complexType name="DotExtensionPoint" 
                   space="pvc.options.marks" 
                   base="pvc.options.marks.MarkExtensionPoint"
                   facets="pvc.options.marks.StrokeBasicFacet
                           pvc.options.marks.FillBasicFacet">
         <c:documentation>
            The class of protovis Dot extension points.
            
            See the associated protovis documentation at
            <c:link to="http://mbostock.github.com/protovis/jsdoc/symbols/pv.Dot.html" />.
        </c:documentation>
        
        <c:property name="shapeAngle" type="number" default="0">
            <c:documentation>
                The rotation angle, in <i>radian</i> units.
                
                Some shapes, 
                like the <c:link to="pvc.options.varia.DotShapeType#Cross" />
                are sensitive to rotation.
            </c:documentation>
        </c:property>
        
        <c:property name="shape" type="pvc.options.varia.DotShapeType">
            <c:documentation>
                The name of the shape that the dot assumes.
            </c:documentation>
        </c:property>
        
        <c:property name="shapeRadius" type="number">
            <c:documentation>
                The radius of the dot, in <i>pixel</i> units.
            </c:documentation>
        </c:property>
        
        <c:property name="shapeSize" type="number">
            <c:documentation>
                The size of the dot, in <i>square pixel</i> units.
                
                The size is proportional to the area of the shape
                and is better suited than the <c:link to="#shapeRadius" /> 
                for representing measures.
                
                For the record: <tt>size = radius * radius</tt>.
            </c:documentation>
        </c:property>

        <c:property name="aspectRatio" type="number" default="1">
            <c:documentation>
                The aspect ratio of the shape.
                A positive number which is the ratio of width to height.
                
                The actual width and height are chosen
                so that the shape has the same area of
                when it has a unit aspect ratio.
            </c:documentation>
        </c:property>
        
    </c:complexType>
</c:model>

=== webdetails/ccc/doc/model/format/customFormat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2030-06-15
 ******************************************************************************* -->
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">

    <c:complexType name="CustomFormat" space="pvc.options.format">
        <c:documentation>
            The options documentation of the custom format class.

            A <i>custom format</i> formats arbitrary values with a
            custom, user supplied, formatting function:
            <c:link to="pvc.options.format.CustomFormat#formatter" />.

            See <c:link to="pvc.options.format.FormatProvider" /> for
            more information on inheritance of formatting configurations.
        </c:documentation>
        <c:property name="formatter" type="pvc.options.varia.DimensionFormatter">
            <c:documentation>
                The custom formatting function.

                The signature of this function is that of a dimension formatter.
            </c:documentation>
        </c:property>
    </c:complexType>
</c:model>

=== webdetails/ccc/doc/model/varia/_varia.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2030-06-15
 ******************************************************************************* -->
<c:model
    xmlns:c="urn:webdetails/com/2012"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">

    <c:space name="pvc.options.varia">
        <c:documentation>
            The namespace of various options-related helper types.
        </c:documentation>
    </c:space>

    <!-- ATOMS -->
    <c:include the="varia/atoms/chartClearSelectionMode.xml" />
    <c:include the="varia/atoms/chartOrientation.xml" />
    <c:include the="varia/atoms/panelAlignment.xml" />
    <c:include the="varia/atoms/panelPosition.xml" />
    <c:include the="varia/atoms/dimensionValueType.xml" />
    <c:include the="varia/atoms/legendClickMode.xml" />
    <c:include the="varia/atoms/dotShapeType.xml" />
    <c:include the="varia/atoms/markAnchor.xml" />
    <c:include the="varia/atoms/wedgeAnchor.xml" />
    <c:include the="varia/atoms/nullInterpolationMode.xml" />
    <c:include the="varia/atoms/axisDomainAlign.xml" />
    <c:include the="varia/atoms/axisDomainScope.xml" />
    <c:include the="varia/atoms/axisDomainRoundingMode.xml" />
    <c:include the="varia/atoms/axisLabelRotationDirection.xml" />
    <c:include the="varia/atoms/axisOverlappedLabelsMode.xml" />
    <c:include the="varia/atoms/pieValuesLabelStyle.xml" />
    <c:include the="varia/atoms/waterDirection.xml" />
    <c:include the="varia/atoms/colorScaleType.xml" />
    <c:include the="varia/atoms/tooltipGravity.xml" />
    <c:include the="varia/atoms/lineAreaInterpolation.xml" />
    <c:include the="varia/atoms/stroke.xml" />
    <c:include the="varia/atoms/text.xml" />
    <c:include the="varia/atoms/rectangleSide.xml" />
    <c:include the="varia/atoms/colorString.xml" />
    <c:include the="varia/atoms/contentOverflow.xml" />
    <c:include the="varia/atoms/treemapLayoutMode.xml" />
    <c:include the="varia/atoms/treemapColorMode.xml" />
    <c:include the="varia/atoms/tooltipAutoContent.xml" />
    <c:include the="varia/atoms/multiChartOverflow.xml" />
    <c:include the="varia/atoms/valuesOverflow.xml" />
    <c:include the="varia/atoms/boxLayoutMode.xml" />
    <c:include the="varia/atoms/pointingMode.xml" />
    <c:include the="varia/atoms/pointingCollapse.xml" />
    <c:include the="varia/atoms/sliceOrder.xml" />
    <c:include the="varia/atoms/sunburstColorMode.xml" />
    <c:include the="varia/atoms/dataTypeCheckingMode.xml" />
    <c:include the="varia/atoms/timeIntervals.xml" />
    <c:include the="varia/atoms/legendOverflow.xml" />

    <!-- FUNCTIONS -->
    <c:include the="varia/functions/colorTransform.xml" />
    <c:include the="varia/functions/dimensionComparer.xml" />
    <c:include the="varia/functions/dimensionConverter.xml" />
    <c:include the="varia/functions/dimensionFormatter.xml" />
    <c:include the="varia/functions/dimensionKey.xml" />
    <c:include the="varia/functions/dimensionsCalculation.xml" />
    <c:include the="varia/functions/dimensionsReader.xml" />
    <c:include the="varia/functions/numberFormatter.xml" />
    <c:include the="varia/functions/selectionChangedAction.xml" />
    <c:include the="varia/functions/standardAction.xml" />
    <c:include the="varia/functions/tooltipFormatter.xml" />
    <c:include the="varia/functions/userSelectionAction.xml" />
    <c:include the="varia/functions/axisTickFormatter.xml" />
    <c:include the="varia/functions/dataWhere.xml" />
    <c:include the="varia/functions/slidingWindowFuns.xml" />

    <!-- COMPLEX TYPES - AUXILIARY -->
    <c:include the="varia/sides.xml" />
    <c:include the="varia/size.xml" />
    <c:include the="varia/tooltip.xml" />
    <c:include the="varia/visualRole.xml" />
    <c:include the="varia/pointing.xml" />
    <c:include the="varia/compatFlags.xml" />

</c:model>

=== webdetails/ccc/doc/model/varia/atoms/markAnchor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2030-06-15
 ******************************************************************************* -->
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:atomType name="MarkAnchor" space="pvc.options.varia" base="string">
        <c:documentation>
            The anchors that are available to all protovis marks,
            with the exception of the Wedge mark 
            (see <c:link to="pvc.options.varia.WedgeAnchor" />).
        </c:documentation>
        
        <c:atom name="Top"    value="'top'" />
        <c:atom name="Left"   value="'left'" />
        <c:atom name="Center" value="'center'" />
        <c:atom name="Bottom" value="'bottom'" />
        <c:atom name="Right"  value="'right'" />
    </c:atomType>
</c:model>

=== webdetails/ccc/doc/model/varia/atoms/axisOverlappedLabelsMode.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2030-06-15
 ******************************************************************************* -->
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:atomType name="AxisOverlappedLabelsMode" space="pvc.options.varia" base="string">
        <c:documentation>
            The layout modes that handle the situation where 
            labels of axes ticks overlap.
        </c:documentation>
        
        <c:atom name="Leave" value="'leave'">
            <c:documentation>
               Let labels overlap.
            </c:documentation>
        </c:atom>
        
        <c:atom name="Hide" value="'hide'">
            <c:documentation>
                Hide labels that overlap.
                
                Between two labels, as many as required are hidden
                until the minimum specified spacing is respected.
                
                In the place of the hidden labels,
                a dot is placed that, 
                when hovering over, 
                indicates the value of the hidden labels.
            </c:documentation>
        </c:atom>

        <c:atom name="Rotate" value="'rotate'">
            <c:documentation>
               Rotate the labels so that they do not overlap.
               If not possible, allows the labels to overlap.
            </c:documentation>
        </c:atom>
        
        <c:atom name="RotateThenHide" value="'rotatethenhide'">
            <c:documentation>
               Rotate the labels so that they do not overlap.
               If not possible, hides the labels that still overlap.
            </c:documentation>
        </c:atom>
    </c:atomType>
</c:model>

=== webdetails/ccc/doc/model/varia/atoms/pointingCollapse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2026 by Pentaho Canada Inc. : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2030-06-15
 ******************************************************************************* -->
<c:model 
    xmlns:c="urn:webdetails/com/2012" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:webdetails/com/2012 ../../../schema/com_2012.xsd"
    xmlns="http://www.w3.org/1999/xhtml">
    
    <c:atomType name="PointingCollapse" space="pvc.options.varia" base="string">
        <c:documentation>
            The names of position components to be ignored when determining the distance
            between the pointer and a visual element.
        </c:documentation>

        <c:atom name="None" value="'none'">
            <c:documentation>
                Considers both the horizontal and vertical distance components.
            </c:documentation>
        </c:atom>

        <c:atom name="X" value="'x'">
            <c:documentation>
                Ignores the horizontal distance.
            </c:documentation>
        </c:atom>

        <c:atom name="Y" value="'y'">
            <c:documentation>
                Ignores the vertical distance.
            </c:documentation>
        </c:atom>
    </c:atomType>
</c:model>
